### PR TITLE
Maintained version from Gangnam Testnet repo

### PR DESCRIPTION
**Pull request by ghost**
For anyone interested on fixing broken stuffs

+ https://github.com/gangnamtestnet/eth-netstats

### CODE REVIEW

**Comment by 5chdn** [comment]
why aren't we collaborating here?

https://github.com/goerli/ethstats-server

**Comment by ghost** [comment]
@5chdn Ugg this one is slightly different with goerli 😂

**Comment by 5chdn** [comment]
what's the difference?

**Comment by ghost** [comment]
I tend to maintain the original version of eth-netstats here, without other functions added

**Pull request closed without merging**
